/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package utillity.view;
import model.*;
import handler.*;
import java.util.ArrayList;

/**
 *
 * @author markh_000
 */
public class StatestikPanel extends javax.swing.JPanel {
private StoreHandler storeHandler;
private SaleHandler saleHandler;
private ArrayList<StateStikGroup> StateList;

    /**
     * Creates new form StatestikPanel
     */
    public StatestikPanel(StoreHandler storeHandler, SaleHandler saleHandler) {
        this.storeHandler =storeHandler;
        this.saleHandler = saleHandler;
        StateList = new ArrayList<>();
        setSize(765, 520);
        initComponents();
    }
    public void setGroup(String type){
        StateList.removeAll(StateList);
        int x = 5;
        int y = 15;
        String TypeName = "";
        jPanel_group.removeAll();
        switch (type) {
            case "Product":
                TypeName = "Mest Solgte";
                StateStikGroup st = new StateStikGroup(TypeName, storeHandler);
                st.setLocation(x, y);
                jPanel_group.add(st);
                st.setVisible(true);
                x = 5 + st.getWidth();
                TypeName = "Størst Indtjening";
                StateStikGroup stete = new StateStikGroup(TypeName, storeHandler);
                stete.setLocation(x , y);
                jPanel_group.add(stete);
                stete.setVisible(true);
                jPanel_group.revalidate();
                break;
            case "Ticket":
                 StateStikGroup s = new StateStikGroup(type, storeHandler);
                break;
            case "Event":
                 StateStikGroup sta = new StateStikGroup(type, storeHandler);
                break;
            case "Viseters":
                 StateStikGroup stat = new StateStikGroup(type, storeHandler);
                break;
            case "Money":
                 StateStikGroup state = new StateStikGroup(type, storeHandler);
                break;
        }
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_ticket = new javax.swing.JButton();
        jButton_evetn = new javax.swing.JButton();
        jButton_product = new javax.swing.JButton();
        jButton_viseters = new javax.swing.JButton();
        jButton_monye = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel_group = new javax.swing.JPanel();

        jButton_ticket.setText("Billetter");
        jButton_ticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ticketActionPerformed(evt);
            }
        });

        jButton_evetn.setText("Eventter");
        jButton_evetn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_evetnActionPerformed(evt);
            }
        });

        jButton_product.setText("Produkter");
        jButton_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_productActionPerformed(evt);
            }
        });

        jButton_viseters.setText("Besøgende");
        jButton_viseters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_visetersActionPerformed(evt);
            }
        });

        jButton_monye.setText("Omsætning");
        jButton_monye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_monyeActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Statestik"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel_group.setBorder(javax.swing.BorderFactory.createTitledBorder("Statestik Type"));

        javax.swing.GroupLayout jPanel_groupLayout = new javax.swing.GroupLayout(jPanel_group);
        jPanel_group.setLayout(jPanel_groupLayout);
        jPanel_groupLayout.setHorizontalGroup(
            jPanel_groupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );
        jPanel_groupLayout.setVerticalGroup(
            jPanel_groupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton_viseters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_product, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_evetn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_ticket, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton_monye, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_group, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_group, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jButton_ticket, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_evetn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_product, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_viseters, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_monye, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(270, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ticketActionPerformed
        setGroup("Ticket");
    }//GEN-LAST:event_jButton_ticketActionPerformed

    private void jButton_evetnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_evetnActionPerformed
        setGroup("Event");
    }//GEN-LAST:event_jButton_evetnActionPerformed

    private void jButton_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_productActionPerformed
        setGroup("Product");
    }//GEN-LAST:event_jButton_productActionPerformed

    private void jButton_visetersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_visetersActionPerformed
        setGroup("Viseters");
    }//GEN-LAST:event_jButton_visetersActionPerformed

    private void jButton_monyeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_monyeActionPerformed
        setGroup("Money");
    }//GEN-LAST:event_jButton_monyeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_evetn;
    private javax.swing.JButton jButton_monye;
    private javax.swing.JButton jButton_product;
    private javax.swing.JButton jButton_ticket;
    private javax.swing.JButton jButton_viseters;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_group;
    // End of variables declaration//GEN-END:variables
}
