/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Panel;

import handler.StoreHandler;
import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.JMenuItem;
import javax.swing.*;
import javax.swing.PopupFactory;

/**
 *
 * @author MarcoPc
 */
public class UserPanel extends javax.swing.JPanel {
    
    private JPopupMenu popup;
    private LogIndPanel logInd;
    private StoreHandler storeHandler;

    public UserPanel(StoreHandler storeHandler1) {
        setSize(new Dimension(380, 50));
        this.storeHandler = storeHandler1;
        popup = new JPopupMenu();
        logInd = new LogIndPanel(storeHandler);
        initComponents();
        setPicAndName();

        
    }
    
    public void setPicAndName() {
        
        try {
            jLabel1.setText(storeHandler.getEmployee().getName());
            jButton_logInd.setEnabled(false);
            jButton_logUd.setEnabled(true);
        } catch (NullPointerException ex) {
            jLabel1.setText("Bruger ikke logget ind");
            jButton_logInd.setEnabled(true);
            jButton_logUd.setEnabled(false);
        }
        
    }
    
    public void logInd() {
        popUpPanel();
        
    }
    
    public void logUd() {
        storeHandler.logoutEmployee();
        setPicAndName();
    }
    public void closepopup(){
        popup.setVisible(false);
    }
    
    public void popUpPanel() {
        
        logInd.setPreferredSize(new Dimension(220, 400));
        
        popup.add(logInd);
        popup.setLocation(250, 220);
        popup.setVisible(true);
 
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_logInd = new javax.swing.JButton();
        jButton_logUd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton_logInd.setText("Log Ind");
        jButton_logInd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_logIndActionPerformed(evt);
            }
        });

        jButton_logUd.setText("Log Ud");
        jButton_logUd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_logUdActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_logUd)
                .addGap(18, 18, 18)
                .addComponent(jButton_logInd)
                .addGap(2, 2, 2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton_logUd, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addComponent(jLabel1))
            .addComponent(jButton_logInd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_logUdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_logUdActionPerformed
        logUd();
        closepopup();
    }//GEN-LAST:event_jButton_logUdActionPerformed

    private void jButton_logIndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_logIndActionPerformed
        popUpPanel();
    }//GEN-LAST:event_jButton_logIndActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_logInd;
    private javax.swing.JButton jButton_logUd;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
