/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utillity.view;

import java.awt.Color;
import java.awt.Graphics;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.EventLine;
import model.ProductLine;
import model.TicketLine;
import utillity.DateFormatTools;
import utillity.Line;
import static utillity.PrintHandler.LINES_PER_PAGE;
import utillity.StatistikHandler;

/**
 *
 * @author MarcoPc
 */
public class StatestikView extends javax.swing.JPanel {

    private String date;
    private DateFormatTools dateTools;
    private StatistikHandler statistikHandler;
    public static final int LINES_PER_PAGE = 23;
    private ArrayList<Line> lines;

    private int xCord;

    /**
     * Creates new form StatestikView
     */
    public StatestikView(ArrayList<Line> lineList, String date) throws ParseException {
        try {
            this.lines = lineList;
            this.date = date;

            statistikHandler = StatistikHandler.getStatistikHandler();
            initComponents();
            setSize(780, 480);

        } catch (SQLException ex) {
            Logger.getLogger(StatestikView.class.getName()).log(Level.SEVERE, null, ex);
        }
        xCord = 10;

    }

    public void drawLines(Graphics g, int page) {
        dateTools = new DateFormatTools();
        Calendar c = dateTools.getDateFromString(date);
        c = dateTools.getNextday(c, 6);

        g.setColor(Color.BLACK);
        g.drawRect(10, 10, 760, 450);
        g.drawLine(10, 70, 770, 70);
        g.drawLine(10, 120, 770, 120);
        g.drawLine(10, 170, 770, 170);
        g.drawLine(10, 220, 770, 220);
        g.drawLine(10, 270, 770, 270);
        g.drawLine(10, 320, 770, 320);

        g.drawLine(130, 10, 130, 460);
        g.drawLine(220, 10, 220, 460);
        g.drawLine(310, 10, 310, 460);
        g.drawLine(400, 10, 400, 460);
        g.drawLine(490, 10, 490, 460);
        g.drawLine(580, 10, 580, 460);
        g.drawLine(670, 10, 670, 460);

        g.drawString(dateTools.getDay(date), 14, 30);
        g.drawString("Til", 55, 45);
        g.drawString(dateTools.getDay(dateTools.getDateFromCal(c)), 14, 60);
        g.drawString("Voksne", 20, (50 + 50));
        g.drawString("Børn", 20, 150);
        g.drawString("Gratister", 20, 200);
        g.drawString("Omvisninger", 20, 250);
        g.drawString("Omvisninger i pers", 20, 300);
        
        for (int i = 0; i < lines.size(); i++) {
            g.drawString(dateTools.getDayLetter(lines.get(i).getTicketDate()), (140 + (i*90)), 30);
            int number = lines.get(i).getTkAdultQu() + lines.get(i).getTkAGroupQu();
            g.drawString(""+number, (160 + (i*90)),  100);
            g.drawString(""+lines.get(i).getTkKidsQu(), (160 + (i*90)),  150);
            g.drawString(""+lines.get(i).getTkFreeQu(), (160 + (i*90)),  200);
            
        }
        System.out.println(dateTools.getDayLetter(date));
//        

//        int lineCount = 0;
//        for (int i = page * LINES_PER_PAGE; i < (page + 1) * LINES_PER_PAGE; i++) {
//            if (i < lines.size()) {
//                int yCoord = 120 + 20 * (i - page * LINES_PER_PAGE);
//                g.drawString(lines.get(i).getText(), 10, yCoord);
//                g.drawString(lines.get(i).getTkAGroupQu() + " kr", 210, yCoord);
//                lineCount++;
//            }
//        }
//        if ((page + 1) * LINES_PER_PAGE >= lines.size()) {
//            int total = 0;
//            for (int i = 0; i < lines.size(); i++) {
//                total = total + lines.get(i).getTkAGroupQu();
//            }
//            g.drawLine(10, lineCount * 20 + 115, 275, lineCount * 20 + 115);
//            g.drawString("Total", 10, 130 + lineCount * 20);
//            g.drawString(total + " kr", 210, 130 + lineCount * 20);
//            g.drawLine(10, lineCount * 20 + 135, 275, lineCount * 20 + 135);
//        }
//        g.drawString("Side " + (page + 1), 10, 300);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel(){
            public void paint(Graphics g){
                super.paint(g);
                drawLines(g,0);
            }
        };

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
