/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package veiw.Panel;
import java.awt.Dimension;
import model.*;
import model.handler.*;
/**
 *
 * @author MarcoPc
 */
public class EventView extends javax.swing.JPanel {
private KurvHandler kurvHandler;
private EventType eventType;
private int plusAntal;
    /**
     * Creates new form EventView
     */
    public EventView(KurvHandler kurvHandler, EventType eventType, int plusAntal) {
        this.kurvHandler = kurvHandler;
        this.eventType = eventType;
        setSize(new Dimension(250, 40));
        initComponents();
        jButton1.setText(eventType.getType());
    }

    public void addticket(){
        if (plusAntal == 1) {
            kurvHandler.setEventTypesList(eventType);
        }else if (plusAntal == 5) {
            for (int i = 0; i < 5; i++) {
                kurvHandler.setEventTypesList(eventType);
            }
        }else if (plusAntal == 10) {
            for (int i = 0; i < 10; i++) {
                kurvHandler.setEventTypesList(eventType);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       addticket();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
